import {
  LuChevronLeft,
  LuMenu,
  LuLaptop,
  LuSmartphone,
  LuMonitor,
  LuCookingPot,
  LuRefrigerator,
  LuHeartPulse,
  LuShirt,
  LuGem,
  LuCar,
  LuStethoscope,
  LuWrench,
  LuBookOpen,
  LuDumbbell,
  LuGift,
  LuShoppingBasket,
  LuBaby,
  LuMapPin,
  LuPawPrint,
  LuSparkles,
  LuCoins,
  LuShoppingBag,
} from "react-icons/lu";

export const menuIcons = {
  amazing: LuSparkles,
  laptop: LuLaptop,
  mobile: LuSmartphone,
  "digital-products": LuMonitor,
  "home-kitchen": LuCookingPot,
  "home-appliances": LuRefrigerator,
  "beauty-health": LuHeartPulse,
  fashion: LuShirt,
  "gold-silver": LuGem,
  "digital-gold": LuCoins,
  automotive: LuCar,
  "medical-health": LuStethoscope,
  "tools-equipment": LuWrench,
  "books-art": LuBookOpen,
  "sports-travel": LuDumbbell,
  "gift-card": LuGift,
  supermarket: LuShoppingBasket,
  "kids-baby-toys": LuBaby,
  "local-products": LuMapPin,
  "pet-shop": LuPawPrint,
  digistyle: LuShoppingBag,
};

export { LuChevronLeft, LuMenu };
