export const GET_CIRCLE_BADGE_REQUEST = "GET_CIRCLE_BADGE_REQUEST";
export const GET_CIRCLE_BADGE_SUCCESS = "GET_CIRCLE_BADGE_SUCCESS";
export const GET_CIRCLE_BADGE_FAILURE = "GET_CIRCLE_BADGE_FAILURE";
